
  <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">HBC</h3>
              <nav>
                <ul class="nav masthead-nav">
                  <!--<li class="active"><a href="#">Home</a></li>-->
                  <li class="dropdown">
                    <a class="dropdown-toggle" aria-expanded="false" aria-haspopup="true" role="button" data-toggle="dropdown" href="#">Questions</a>
                      <ul class="dropdown-menu">
                        <li><a href="Question1.htm">Question 1</a></li>
                        <li><a href="Question2.htm">Question 2</a></li>
                        <li><a href="#">Question 3</a></li>
                      </ul>
                   </li>
                </ul>
              </nav>
            </div>
          </div>